### PR TITLE
Fixed issue with cache ttl for content-type application/json

### PR DESCRIPTION
**Pull request by albertdahlin**
This fixes some issues with ajax requests getting cached with the ttl for static content (1w) instead of the settings in Magento.

### CODE REVIEW

**Comment by jonathanselander** [comment]
@albertdahlin thanks - however i think it makes sense to use ESI in json responses as well

**Comment by albertdahlin** [comment]
I removed esi from json responses since the inserted esi content might break json formatting, eg. inserting any html block output containing ", new line char,  etc.
Also, the double quotes of the esi src attribute will be escaped in a json string. I don't know if / how varnish handles this.

**Comment by jonathanselander** [comment]
@albertdahlin the cool thing with ESI is that it runs separately from everything, so it's actually completely fine to include it in the body. i would move it to the previous if clause and then merge

**Comment by albertdahlin** [comment]
@jonathanselander 
I still see some problems with doing ESI replacement on the json format. Consider the following example:
#### Problem 1:
```php
$data = array(
    'key1' => $cartBlock->toHtml(),
    'key2'  => 'something else'
);
echo json_encode($data);
```
The json output will be:
```
{
    "key1":"<esi:include src=\"http:\/\/example.com\/madecache.....\"\/>",
    "key2":"something else"
}
```
Note that the ESI src attribute has some characters escaped, this is done by json_encode. Does varnish handle this?

If it does we still have to consider this:
#### Problem 2:
The data replacing the ESI tag needs to be in valid json format. Inserting a newline or " without escaping it would break the json.
Since this module works with raw block output the data is going to be in html format, which will break json formatting.

Just some thoughts.

**Comment by albertdahlin** [comment]
I can now verify that esi does not work on json encoded html. We have an implementation where the cart link block is rendered and returned as json encoded html. The esi tag slips through, I guess this is due to varnish not recognizing it.

This is the response I get in my browser:
```
{
"header.cartlink":"<esi:include src=\"http:\/\/some-site.dev\/se\/madecache\/varnish\/esi\/hash\/5d8259e581fd147e53e5b...
}
```

**Comment by jonathanselander** [comment]
@albertdahlin If you control the ajax request, i would rather setEsi(0) on the block before rendering it

**Pull request closed without merging**
